
import React, { lazy } from 'react';
import { 
  LayoutDashboard, 
  Users, 
  UserCircle, 
  Bell, 
  BookOpen, 
  Settings, 
  ShieldCheck, 
  Database, 
  Lock, 
  User, 
  Layers, 
  FileCheck, 
  ClipboardList, 
  BarChart3, 
  Grid, 
  Table, 
  AlertOctagon, 
  Users2,
  Home,
  Shield,
  Search,
  RefreshCw,
  LogOut,
  Menu,
  X,
  ChevronDown,
  ChevronUp,
  Plus,
  Edit,
  Trash2,
  Copy,
  ArrowUpDown,
  CheckCircle2,
  XCircle,
  BrainCircuit,
  AlertTriangle,
  ZoomIn,
  ZoomOut,
  RotateCw,
  RotateCcw,
  Maximize,
  Move,
  FileQuestion,
  FileText,
  FileWarning,
  Clock,
  CheckCircle,
  UserCheck,
  UserX,
  Hourglass,
  ExternalLink,
  GitCompare,
  Play,
  Loader,
  Loader2,
  Eraser,
  Printer,
  Calendar,
  CalendarCheck,
  CalendarX,
  Phone,
  MapPin,
  ChevronLeft,
  ChevronRight,
  Eye,
  EyeOff,
  Edit2,
  Wrench,
  Save,
  ArrowRight,
  SlidersHorizontal,
  Monitor,
  Sun,
  Moon,
  Building,
  BookKey,
  Stethoscope,
  BookHeart,
  Palette,
  FileEdit,
  Activity,
  Heart,
  ListTodo,
  ClipboardCheck,
  FileSpreadsheet,
  LayoutTemplate,
  PenTool,
  BedDouble,
  Check,
  Stamp,
  Scale,
  Briefcase,
  FileSearch,
  SearchCheck
} from 'lucide-react';

// Custom Inverted Tick (Mirrored and Rotated Check mark used by CAs/Auditors)
const AuditTick = (props: any) => (
  <Check {...props} style={{ transform: 'scaleX(-1) rotate(250deg)', ...props.style }} />
);

export const ICONS: { [key: string]: React.ReactElement } = {
  'LayoutDashboard': <LayoutDashboard />,
  'Users': <Users />,
  'UserCircle': <UserCircle />,
  'BedDouble': <BedDouble />,
  'Bell': <Bell />,
  'BookOpen': <BookOpen />,
  'Settings': <Settings />,
  'ShieldCheck': <ShieldCheck />,
  'Database': <Database />,
  'Lock': <Lock />,
  'User': <User />,
  'Layers': <Layers />,
  'FileCheck': <FileCheck />,
  'ClipboardList': <ClipboardList />,
  'BarChart3': <BarChart3 />,
  'Grid': <Grid />,
  'Table': <Table />,
  'AlertOctagon': <AlertOctagon />,
  'Users2': <Users2 />,
  'Home': <Home />,
  'Shield': <Shield />,
  'Search': <Search />,
  'RefreshCw': <RefreshCw />,
  'LogOut': <LogOut />,
  'Menu': <Menu />,
  'X': <X />,
  'ChevronDown': <ChevronDown />,
  'ChevronUp': <ChevronUp />,
  'Plus': <Plus />,
  'Edit': <Edit />,
  'Trash2': <Trash2 />,
  'Copy': <Copy />,
  'ArrowUpDown': <ArrowUpDown />,
  'CheckCircle2': <CheckCircle2 />,
  'XCircle': <XCircle />,
  'BrainCircuit': <BrainCircuit />,
  'AlertTriangle': <AlertTriangle />,
  'ZoomIn': <ZoomIn />,
  'ZoomOut': <ZoomOut />,
  'RotateCw': <RotateCw />,
  'RotateCcw': <RotateCcw />,
  'Maximize': <Maximize />,
  'Move': <Move />,
  'FileQuestion': <FileQuestion />,
  'FileText': <FileText />,
  'FileWarning': <FileWarning />,
  'Clock': <Clock />,
  'CheckCircle': <CheckCircle />,
  'UserCheck': <UserCheck />,
  'UserX': <UserX />,
  'Hourglass': <Hourglass />,
  'ExternalLink': <ExternalLink />,
  'GitCompare': <GitCompare />,
  'Play': <Play />,
  'Loader': <Loader />,
  'Loader2': <Loader2 />,
  'Eraser': <Eraser />,
  'Printer': <Printer />,
  'Calendar': <Calendar />,
  'CalendarCheck': <CalendarCheck />,
  'CalendarX': <CalendarX />,
  'Phone': <Phone />,
  'MapPin': <MapPin />,
  'ChevronLeft': <ChevronLeft />,
  'ChevronRight': <ChevronRight />,
  'Eye': <Eye />,
  'EyeOff': <EyeOff />,
  'Edit2': <Edit2 />,
  'Wrench': <Wrench />,
  'Save': <Save />,
  'ArrowRight': <ArrowRight />,
  'SlidersHorizontal': <SlidersHorizontal />,
  'Monitor': <Monitor />,
  'Sun': <Sun />,
  'Moon': <Moon />,
  'Building': <Building />,
  'BookKey': <BookKey />,
  'Stethoscope': <Stethoscope />,
  'BookHeart': <BookHeart />,
  'Palette': <Palette />,
  'FileEdit': <FileEdit />,
  'Activity': <Activity />,
  'Heart': <Heart />,
  'ListTodo': <ListTodo />,
  'ClipboardCheck': <ClipboardCheck />,
  'FileSpreadsheet': <FileSpreadsheet />,
  'LayoutTemplate': <LayoutTemplate />,
  'PenTool': <PenTool />,
  'AuditTick': <AuditTick />,
  'Stamp': <Stamp />,
  'Scale': <Scale />,
  'Briefcase': <Briefcase />,
  'FileSearch': <FileSearch />,
  'SearchCheck': <SearchCheck />
};

const DashboardView = lazy(() => import('./DashboardView'));
const UserManagement = lazy(() => import('../users/UserManagement'));
const PeopleManagement = lazy(() => import('../people/PeopleManagement'));
const NotificationTemplatesManagement = lazy(() => import('../notifications/NotificationTemplatesManagement'));
const DataDictionary = lazy(() => import('../smr/DataDictionary'));
const SettingsManagement = lazy(() => import('../settings/SettingsManagement'));
const AppConfigManagement = lazy(() => import('../app-config/AppConfigManagement'));
const SMREditor = lazy(() => import('../smr/SMREditor'));
const MastersManagement = lazy(() => import('../masters/MastersManagement'));
const MyProfile = lazy(() => import('../profile/MyProfile'));
const UIShowcase = lazy(() => import('../common/UIShowcase'));
const CollectionBoxAudit = lazy(() => import('../aiac/CollectionBoxAudit'));
const ReportsDashboard = lazy(() => import('../reports/ReportsDashboard'));
const AccountSubmissionsDashboard = lazy(() => import('../account-submissions/AccountSubmissionsDashboard'));
const PermissionMatrix = lazy(() => import('../admin/PermissionMatrix'));
const AccountStatusPivot = lazy(() => import('../reports/AccountStatusPivot'));
const VouchingStatsDashboard = lazy(() => import('../vouching-stats/VouchingStatsDashboard')); // NEW

// NEW MODULES
const DataSourceManager = lazy(() => import('../admin/DataSourceManager'));
const ReportBuilder = lazy(() => import('../reports/ReportBuilder'));
const CustomReportWrapper = lazy(() => import('../reports/CustomReportWrapper'));

const PlaceholderComponent: React.FC = () => (
    <div className="p-8 text-center text-gray-500">
        <h2 className="text-2xl font-bold mb-2">Module Under Development</h2>
        <p>This component is a placeholder for a future feature.</p>
    </div>
);

const Placeholder = lazy(() => Promise.resolve({ default: PlaceholderComponent }));

export const COMPONENTS: { [key: string]: React.LazyExoticComponent<React.ComponentType<any>> } = {
  'dashboard': DashboardView,
  'users': UserManagement,
  'people': PeopleManagement, 
  'room-availability': Placeholder,
  'notification-templates': NotificationTemplatesManagement,
  'data-dictionary': DataDictionary,
  'settings': SettingsManagement,
  'placeholder': Placeholder,
  'app-config': AppConfigManagement,
  'smr-editor': SMREditor,
  'masters-management': MastersManagement,
  'my-profile': MyProfile,
  'ui-showcase': UIShowcase,
  'audit-collection-box': CollectionBoxAudit,
  'reports': ReportsDashboard, 
  'account-submissions': AccountSubmissionsDashboard,
  'flats': Placeholder,
  'rooms': Placeholder,
  'beds': Placeholder,
  'allotments': Placeholder,
  'allotment-history': Placeholder,
  'reservations': Placeholder,
  'physio-workstation': Placeholder,
  'vitals-workstation': Placeholder,
  'report-floor-occupancy': Placeholder,
  'report-bed-matrix': Placeholder,
  'report-occupancy-details': Placeholder,
  'report-duplicate-audit': Placeholder,
  'report-event-occupancy': Placeholder,
  'report-account-pivot': AccountStatusPivot, 
  'permission-matrix': PermissionMatrix, 
  'inventory-config': Placeholder,
  'inventory-audit': Placeholder,
  'data-sources': DataSourceManager,
  'report-builder': ReportBuilder,
  'custom-report-viewer': CustomReportWrapper,
  'vouching-stats': VouchingStatsDashboard // NEW
};
